# environment variable name
LISTEN_PORT = 'LISTEN_PORT'
TIMEZONE = 'TIMEZONE'
ORION_ENDPOINT = 'ORION_ENDPOINT'
ORION_TOKEN = 'ORION_TOKEN'
FIWARE_SERVICE = 'FIWARE_SERVICE'
DELIVERY_ROBOT_SERVICEPATH = 'DELIVERY_ROBOT_SERVICEPATH'
DELIVERY_ROBOT_TYPE = 'DELIVERY_ROBOT_TYPE'
DELIVERY_ROBOT_01 = 'DELIVERY_ROBOT_01'

# constants
ORION_BAAE_PATH = '/v2/entities/'
