# environment variable name
LISTEN_PORT = 'LISTEN_PORT'
TIMEZONE = 'TIMEZONE'
ORION_ENDPOINT = 'ORION_ENDPOINT'
ORION_TOKEN = 'ORION_TOKEN'
FIWARE_SERVICE = 'FIWARE_SERVICE'
DELIVERY_ROBOT_SERVICEPATH = 'DELIVERY_ROBOT_SERVICEPATH'
DELIVERY_ROBOT_TYPE = 'DELIVERY_ROBOT_TYPE'
DELIVERY_ROBOT_01 = 'DELIVERY_ROBOT_01'
CORS_ORIGINS = 'CORS_ORIGINS'

# constants
ORION_BASE_PATH = '/v2/entities/'
PLACE_TYPE = 'place'
ROUTE_PLAN_TYPE = 'route_plan'
VIA_SEPARATOR = '|'

# Robot mode
MODE_INIT = ' '
MODE_NAVI = 'navi'
MODE_STANDBY = 'standby'
MODE_ERROR = 'error'
